server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/lab2
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate